experiment:
  experiment_name: 'matching'

training:
  start_epoch: 0
  num_epochs: 15
  batch_size: 32
  device: 'cuda:1'
  num_workers: 2
  checkpoint_interval: 1
  checkpoint_dir: '/home/jovyan/nkiselev/ddorin/project/Pairwise-Image-Matching/checkpoint_dir/vit_15ep_unfreeze'
  contrastive_regularizer: True

data:
  tensorboard_logdir: '/home/jovyan/nkiselev/ddorin/project/Pairwise-Image-Matching/logs/vit_15ep_unfreeze'

model:
  model_name: 'vit'
  initialization_weights_path: null
  use_advanced_head: True
  freeze_encoder: False

optimizer:
  name: 'AdamW'  # Выберите 'Adam' или 'AdamW'
  lr: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]

scheduler:
  milestones: [5, 10]
  gamma: 0.5

regularizer:
  margin: 0.5
  lambda: 0.05