experiment:
  experiment_name: 'matching'

training:
  start_epoch: 0
  num_epochs: 300
  batch_size: 32
  device: 'cuda'
  num_workers: 2
  checkpoint_interval: 1
  contrastive_regularizer: True

data:
  tensorboard_logdir: '/logs'

model:
  initialization_weights_path: null
  checkpoint_dir: '/checkpoint_dir/first_experiment'
  use_advanced_head: True
  freeze_encoder: True

optimizer:
  name: 'AdamW'  # Выберите 'Adam' или 'AdamW'
  lr: 0.0001
  weight_decay: 0.00001
  betas: [0.9, 0.999]

scheduler:
  milestones: [18000, 36000, 45000]
  gamma: 0.5

regularizer:
  margin: 0.5
  lambda: 0.05